server:
  port: 8888
spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user:
      name: configuser
      password: configPass$1234
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravindracs1986/config
          force-pull: true # pull the latest code from GIT in case the local repo has some issues and couldn't able to update the repo
          skipSslValidation: true # Git Server SSL validation can be disabled
          timeout: 10 #HTTP connection timeout (in seconds)
          username: ravindracs1986
          password: Naman1kot@
encrypt:
  key: <your security key go over here>